name: Run Scheduled Events Docker

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-scheduled-events:
    uses: Cemberk/fork-maintenance-system/.github/workflows/fork-maintenance-action.yml@artifacts
    with:
      #github_token: ${{ secrets.GITHUB_TOKEN }}
      upstream_repo: 'https://github.com/bitsandbytes-foundation/bitsandbytes'
      #schedule_json: ${{ secrets.SCHEDULE_CONFIG }}  # Your JSON content
      pr_branch_prefix: 'scheduled-merge'
      requirements_command: 'apt-get install -y build-essential cmake && pip install --upgrade pip && pip install einops lion_pytorch accelerate && ls && pwd && pip install git+https://github.com/ROCm/transformers.git && mv requirements-dev.txt requirements.txt || true && pip install -r requirements.txt && cmake -DCOMPUTE_BACKEND=hip -S . && make && pip install .'
      unit_test_command: 'pytest -vvv ./tests/ 2>&1 | tee BitsAndBytes_UT_summary.log'
      performance_test_command: 'echo \"python\"'
      docker_image: 'rocm/pytorch:latest'
      docker_options: '--device=/dev/kfd --device=/dev/dri --group-add video --shm-size 16G --network=host'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      schedule_json: ${{ secrets.SCHEDULE_CONFIG }}

    #FOR COMPOSITE WORKFLOW TYPE 
    #runs-on:  gfx90a
    #env:
    #  SCHEDULE_CONFIG: ${{ secrets.SCHEDULE_CONFIG }} # Secret storing the schedule JSON
    #steps:
    #  - name: Fork Maintenance System
    #    uses: Cemberk/Fork-Maintenance-System@artifacts
    #    with:
    #      github_token: ${{ secrets.CRED_TOKEN }}
    #      upstream_repo: "https://github.com/bitsandbytes-foundation/bitsandbytes"
    #      schedule_json: |
    #        ${{ env.SCHEDULE_CONFIG }}
    #      pr_branch_prefix: "scheduled-merge"
    #      requirements_command: >
    #        apt-get install -y build-essential cmake && pip install --upgrade pip && pip install einops lion_pytorch accelerate && ls && pwd && pip install git+https://github.com/ROCm/transformers.git && mv requirements-dev.txt requirements.txt || true && pip install -r requirements.txt && cmake -DCOMPUTE_BACKEND=hip -S . && make && pip install .
    #      unit_test_command: pytest -vvv ./tests/ 2>&1 | tee BitsAndBytes_UT_summary.log
    #      performance_test_command: echo \"python\"
    #      docker_image: rocm/pytorch:latest
    #      docker_options: --device=/dev/kfd --device=/dev/dri --group-add video --shm-size 16G --network=host

